# Generated by Django 4.1 on 2022-09-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bank',
            new_name='banks',
        ),
    ]
